vueX format
TigranHovhannisyan300107/todolist pull request #6
Opened 2021-05-10 16:09 UTC by TigranHovhannisyan300107

2021-05-11 12:32 UTC, Vahe101 commented on src/components/ToDo.vue
> +  computed:mapGetters(["arrListState","itemState"]),
always adhere to code style standards( semicolons, commas, spaces, and lines )

2021-05-11 12:32 UTC, Vahe101 commented on src/components/ToDo.vue
> +       <li v-for="(item, index) in arrListState" :key="item">
use indexes as a key instead of an element

2021-05-11 12:32 UTC, Vahe101 commented on src/components/ToDo.vue
> +         <button class="btn" v-on:click="removlist(index)">Delete</button>
"v-on click" use the new format

2021-05-11 12:32 UTC, Vahe101 commented on src/components/ToDo.vue
> +import {mapGetters,mapMutations} from "vuex"
when importing, first import the default packages and only then your components

2021-05-12 14:58 UTC, edotnet requested changes
Please pay more attention on code formatting and naming

2021-05-12 14:58 UTC, edotnet commented on src/components/ToDo.vue
> +            <input type="text" v-if="getId == item.id" v-model="item.title" />
`v-if="getId == item.id"` was added for each element in `savelist` div. Does it make sense to add the checking on parent element instead of having it on every child?

2021-05-12 14:58 UTC, edotnet commented on src/components/ToDo.vue
> +      this.ed = true;
Use meaningful names. `ed` doesnt make sense

2021-05-12 14:58 UTC, edotnet commented on src/components/ToDo.vue
> +	box-shadow:inset 0px -3px 7px 0px #fafafa;
fix formatting

2021-05-12 14:58 UTC, edotnet commented on src/components/ToDo.vue
> +.myButton:hover {
add new line between styles

2021-05-12 14:58 UTC, edotnet commented on src/components/TodoList.vue
> +    <input  type="text" v-model="title" @keypress.enter="sub" placeholder="Title" />
have this inputs inside `form` element. Then you wouldnt need `@keypress.enter` event handler.

2021-05-12 14:58 UTC, edotnet commented on src/components/TodoList.vue
> +    <button class="add" @click="sub">Add List</button>
put this inside `form` and make it's type to be `submit`

2021-05-12 14:58 UTC, edotnet commented on src/components/TodoList.vue
> +    ...mapMutations(["titelState", "addToDo","disState"]),
should be `titleState`

2021-05-12 14:58 UTC, edotnet commented on src/components/TodoList.vue
> +
remove extra line

2021-05-12 14:58 UTC, edotnet commented on src/components/TodoList.vue
> +.myButton:hover {
add new lines

2021-05-12 14:58 UTC, edotnet commented on src/store/index.js
> +
remove comment and empty lines

2021-05-12 14:58 UTC, edotnet commented on src/store/index.js
> +export default new Vuex.Store({
Try to separate the store into different modules

2021-05-12 16:54 UTC, Vahe101 commented on src/components/ToDo.vue
> +    saveedit() {
please see the rule for naming variables, functions, etc.

2021-05-12 16:54 UTC, Vahe101 commented on src/components/ToDo.vue
> +          <button class="edit" @click="edit(item.id)">Edit</button>
when editing title, and description cannot be empty, please check that case

2021-05-12 16:54 UTC, Vahe101 commented on src/store/index.js
> +         dbdiscrip(state) {
this is also a bad example of naming

2021-05-12 16:54 UTC, Vahe101 commented on src/store/index.js
> +        dblist(state) {
and this name too

2021-05-12 16:54 UTC, Vahe101 commented on src/store/index.js
> +        dbtitle(state) {
and this too

2021-05-13 06:42 UTC, TigranHovhannisyan300107 commented on src/components/ToDo.vue
> +            <input type="text" v-if="getId == item.id" v-model="item.title" />
done

2021-05-13 07:16 UTC, TigranHovhannisyan300107 commented on src/components/ToDo.vue
> +      this.ed = true;
done

2021-05-13 07:16 UTC, TigranHovhannisyan300107 commented on src/components/ToDo.vue
> +	box-shadow:inset 0px -3px 7px 0px #fafafa;
done

2021-05-13 07:16 UTC, TigranHovhannisyan300107 commented on src/components/ToDo.vue
> +.myButton:hover {
done

2021-05-13 07:16 UTC, TigranHovhannisyan300107 commented on src/components/TodoList.vue
> +    <input  type="text" v-model="title" @keypress.enter="sub" placeholder="Title" />
done

2021-05-13 07:17 UTC, TigranHovhannisyan300107 commented on src/components/TodoList.vue
> +
done

2021-05-13 07:18 UTC, TigranHovhannisyan300107 commented on src/components/TodoList.vue
> +
dnoe

2021-05-13 07:18 UTC, TigranHovhannisyan300107 commented on src/components/TodoList.vue
> +.myButton:hover {
done

2021-05-13 07:19 UTC, TigranHovhannisyan300107 commented on src/store/index.js
> +
done

2021-05-13 07:20 UTC, TigranHovhannisyan300107 commented on src/store/index.js
> +export default new Vuex.Store({
done

2021-05-13 07:22 UTC, TigranHovhannisyan300107 commented on src/store/index.js
> +        dbtitle(state) {
done

2021-05-13 07:22 UTC, TigranHovhannisyan300107 commented on src/store/index.js
> +        dblist(state) {
done

2021-05-13 07:22 UTC, TigranHovhannisyan300107 commented on src/store/index.js
> +         dbdiscrip(state) {
done

2021-05-13 07:27 UTC, TigranHovhannisyan300107 commented on src/components/ToDo.vue
> +    saveedit() {
done

2021-05-13 07:31 UTC, TigranHovhannisyan300107 commented on src/components/ToDo.vue
> +          <button class="edit" @click="edit(item.id)">Edit</button>
done

2021-05-13 08:31 UTC, TigranHovhannisyan300107 commented on src/components/TodoList.vue
> +    ...mapMutations(["titelState", "addToDo","disState"]),
done

2021-05-13 09:09 UTC, Vahe101 commented on src/components/ToDo.vue
> +    editList(i) {
I can still edit and save blank description and title

2021-05-13 09:09 UTC, Vahe101 commented on src/components/TodoList.vue
> +    <button class="add" @click="sub">Add List</button>
Edik's comment was not about removing the input press, but about using the "form" tag, as this tag already has the default logic of pressing the key "enter"

2021-05-13 09:09 UTC, Vahe101 commented on src/main.js
> +import App from './App.vue';
use 1 import method. with @/ or with ./

2021-05-13 16:19 UTC, merged